### ISSUE TITLE
"No module named pip"

### ISSUE THREAD

**Issue by GuyPaddock** [sicxu/Deep3DFaceRecon_pytorch#184]
When following the installation steps and running `conda env create -f environment.yml`, the command fails with this error:
```
Installing pip dependencies: \ Ran pip subprocess with arguments:
['/home/guyep/miniconda3/envs/deep3d_pytorch/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/guyep/playground/Deep3DFaceRecon_pytorch/condaenv.2duqmury.requirements.txt', '--exists-action=b']
Pip subprocess output:

Pip subprocess error:
/home/guyep/miniconda3/envs/deep3d_pytorch/bin/python: No module named pip
                                                                                                                                                                                           failed

CondaEnvException: Pip failed
```

It looks like I'm not alone:
https://stackoverflow.com/questions/78326712/no-module-named-pip

**Comment by Cosmo-klara** [comment]
> When following the installation steps and running `conda env create -f environment.yml`, the command fails with this error:
> 
> ```
> Installing pip dependencies: \ Ran pip subprocess with arguments:
> ['/home/guyep/miniconda3/envs/deep3d_pytorch/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/guyep/playground/Deep3DFaceRecon_pytorch/condaenv.2duqmury.requirements.txt', '--exists-action=b']
> Pip subprocess output:
> 
> Pip subprocess error:
> /home/guyep/miniconda3/envs/deep3d_pytorch/bin/python: No module named pip
> 
> CondaEnvException: Pip failed
> ```
> 
> It looks like I'm not alone: https://stackoverflow.com/questions/78326712/no-module-named-pip

@GuyPaddock 
Maybe this will help. ( Simply changed the pip version，Maybe it's also related to the order? I'm not really sure, but it works for me. )


```yml
name: deep3d_pytorch
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r

dependencies:
  - python=3.6
  - pip=21.0
  - pytorch=1.6.0
  - torchvision=0.7.0
  - numpy=1.18.1
  - scikit-image=0.16.2
  - scipy=1.4.1
  - pillow=6.2.1
  - ipython=7.13.0
  - yaml=0.1.7
  - pip:
    - matplotlib==2.2.5
    - opencv-python==3.4.9.33
    - tensorboard==1.15.0
    - tensorflow==1.15.0
    - kornia==0.5.5
    - dominate==2.6.0
    - trimesh==3.9.20
 ```
